### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by raghavrv**
(merge master for #9075) 

@agramfort this should fix that PR

### CODE REVIEW

**Comment by agramfort** [comment]
did you see that Y is actually used below? so if we just remove it we remove a feature of the PLS class?

**Comment by raghavrv** [comment]
If `Y` is passed by the user (!= 'deprecated'), then the value is retained after deprecation warning. The current functionality is retained

If `Y` was not passed, we set `Y=None`.

Am I missing something?

**Comment by raghavrv** [comment]
And all the current PLS tests seem to pass after this fix.

**Comment by raghavrv** [comment]
@agramfort could you merge this. This should fix the CIs.

**Pull request merged**
